modLoader="javafml"

loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]

modId="${mod_id}"

version="${mod_version}"
side="CLIENT"
displayName="${mod_name}"

authors="FloofHips"

description='''
Changes ice so it conforms to the biome water tint
'''

#[[mixins]]
#config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
